before:
  hooks:
    - go mod download

builds:
  - binary: docker-cni
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.REVISION={{.Commit}}
      - -X main.VERSION={{.Env.VERSION}}
      - -X main.BUILTAT={{.Date}}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - replacements:
      linux: Linux
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
